export { default as Login } from './login/Login'
export { default as Signup } from './signup/Signup'
export { default as Home } from './home/Home'
export { default as NotFound } from './page-not-found/PageNotFound'
export { default as History } from './history/History'
